[package]
name = "algorithm-examples"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
cpu-time = "1.0.0"
log = "0.4.11"
simplelog = "0.8.0"